(ns anaphora.examples
  [clojure.tools.analyzer.jvm :refer [analyze]])

(def example (analyze '(fn [x y] (fn [a b] (+ x a)))))
  
{:children [:methods],
 :body? true,
 :return-tag clojure.lang.AFunction,
 :op :fn,
 :env {:context :ctx/expr,
       :locals {},
       :ns anaphora.macros,
       :column 17,
       :line 1,
       :file "/tmp/form-init4625432850048136597.clj"},
 :o-tag clojure.lang.AFunction,
 :variadic? false,
 :methods [{:children [:params :body],
            :loop-id loop_20645,
            :arglist [x y],
            :params [{:name x__#0,
                      :op :binding,
                      :env {:context :ctx/expr,
                            :locals {},
                            :ns anaphora.macros,
                            :once false,
                            :file "/tmp/form-init4625432850048136597.clj",
                            :column 17,
                            :line 1},
                      :o-tag java.lang.Object,
                      :variadic? false,
                      :arg-id 0,
                      :form x,
                      :tag java.lang.Object,
                      :atom #object[clojure.lang.Atom
                                    "0x5ed19b"
                                    {:status :ready,
                                     :val {:tag java.lang.Object}}],
                      :local :arg}
                     {:name y__#0,
                      :op :binding,
                      :env {:context :ctx/expr,
                            :locals {},
                            :ns anaphora.macros,
                            :once false,
                            :file "/tmp/form-init4625432850048136597.clj",
                            :column 17,
                            :line 1},
                      :o-tag java.lang.Object,
                      :variadic? false,
                      :arg-id 1,
                      :form y,
                      :tag java.lang.Object,
                      :atom #object[clojure.lang.Atom
                                    "0x4b73e816"
                                    {:status :ready,
                                     :val {:tag java.lang.Object}}],
                      :local :arg}],
            :fixed-arity 2,
            :op :fn-method,
            :env {:context :ctx/expr,
                  :locals {},
                  :ns anaphora.macros,
                  :once false,
                  :file "/tmp/form-init4625432850048136597.clj",
                  :column 17,
                  :line 1},
            :o-tag java.lang.Object,
            :variadic? false,
            :form ([x y] (fn [a b] (+ x a))),
            :tag java.lang.Object,
            :body {:children [:methods],
                   :body? true,
                   :return-tag java.lang.Number,
                   :op :fn,
                   :env {:loop-locals 2,
                         :locals {x {:form x,
                                     :name x,
                                     :variadic? false,
                                     :op :binding,
                                     :arg-id 0,
                                     :local :arg},
                                  y {:form y,
                                     :name y,
                                     :variadic? false,
                                     :op :binding,
                                     :arg-id 1,
                                     :local :arg}},
                         :ns anaphora.macros,
                         :loop-id loop_20645,
                         :file "/tmp/form-init4625432850048136597.clj",
                         :column 27,
                         :line 1,
                         :once false,
                         :context :ctx/expr},
                   :o-tag clojure.lang.AFunction,
                   :variadic? false,
                   :methods [{:children [:params :body],
                              :loop-id loop_20646,
                              :arglist [a b],
                              :params [{:name a__#0,
                                        :op :binding,
                                        :env {:loop-locals 2,
                                              :locals {x {:form x,
                                                          :name x,
                                                          :variadic? false,
                                                          :op :binding,
                                                          :arg-id 0,
                                                          :local :arg},
                                                       y {:form y,
                                                          :name y,
                                                          :variadic? false,
                                                          :op :binding,
                                                          :arg-id 1,
                                                          :local :arg}},
                                              :ns anaphora.macros,
                                              :loop-id loop_20645,
                                              :file "/tmp/form-init4625432850048136597.clj",
                                              :column 27,
                                              :line 1,
                                              :once false,
                                              :context :ctx/return},
                                        :o-tag java.lang.Object,
                                        :variadic? false,
                                        :arg-id 0,
                                        :form a,
                                        :tag java.lang.Object,
                                        :atom #object[clojure.lang.Atom
                                                      "0x1fc9405c"
                                                      {:status :ready,
                                                       :val {:tag java.lang.Object}}],
                                        :local :arg}
                                       {:name b__#0,
                                        :op :binding,
                                        :env {:loop-locals 2,
                                              :locals {x {:form x,
                                                          :name x,
                                                          :variadic? false,
                                                          :op :binding,
                                                          :arg-id 0,
                                                          :local :arg},
                                                       y {:form y,
                                                          :name y,
                                                          :variadic? false,
                                                          :op :binding,
                                                          :arg-id 1,
                                                          :local :arg}},
                                              :ns anaphora.macros,
                                              :loop-id loop_20645,
                                              :file "/tmp/form-init4625432850048136597.clj",
                                              :column 27,
                                              :line 1,
                                              :once false,
                                              :context :ctx/return},
                                        :o-tag java.lang.Object,
                                        :variadic? false,
                                        :arg-id 1,
                                        :form b,
                                        :tag java.lang.Object,
                                        :atom #object[clojure.lang.Atom
                                                      "0x6d7ef9c4"
                                                      {:status :ready,
                                                       :val {:tag java.lang.Object}}],
                                        :local :arg}],
                              :fixed-arity 2,
                              :op :fn-method,
                              :env {:loop-locals 2,
                                    :locals {x {:form x,
                                                :name x,
                                                :variadic? false,
                                                :op :binding,
                                                :arg-id 0,
                                                :local :arg},
                                             y {:form y,
                                                :name y,
                                                :variadic? false,
                                                :op :binding,
                                                :arg-id 1,
                                                :local :arg}},
                                    :ns anaphora.macros,
                                    :loop-id loop_20645,
                                    :file "/tmp/form-init4625432850048136597.clj",
                                    :column 27,
                                    :line 1,
                                    :once false,
                                    :context :ctx/return},
                              :o-tag java.lang.Object,
                              :variadic? false,
                              :form ([a b] (+ x a)),
                              :tag java.lang.Object,
                              :body {:args [{:children [],
                                             :name x__#0,
                                             :op :local,
                                             :env {:loop-locals 2,
                                                   :locals {x {:form x,
                                                               :name x,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 0,
                                                               :local :arg},
                                                            y {:form y,
                                                               :name y,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 1,
                                                               :local :arg},
                                                            a {:form a,
                                                               :name a,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 0,
                                                               :local :arg},
                                                            b {:form b,
                                                               :name b,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 1,
                                                               :local :arg}},
                                                   :ns anaphora.macros,
                                                   :loop-id loop_20646,
                                                   :file "/tmp/form-init4625432850048136597.clj",
                                                   :column 37,
                                                   :line 1,
                                                   :once false,
                                                   :context :ctx/expr},
                                             :o-tag java.lang.Object,
                                             :variadic? false,
                                             :arg-id 0,
                                             :form x,
                                             :tag java.lang.Object,
                                             :atom #object[clojure.lang.Atom
                                                           "0x5ed19b"
                                                           {:status :ready,
                                                            :val {:tag java.lang.Object}}],
                                             :local :arg,
                                             :assignable? false}
                                            {:children [],
                                             :name a__#0,
                                             :op :local,
                                             :env {:loop-locals 2,
                                                   :locals {x {:form x,
                                                               :name x,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 0,
                                                               :local :arg},
                                                            y {:form y,
                                                               :name y,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 1,
                                                               :local :arg},
                                                            a {:form a,
                                                               :name a,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 0,
                                                               :local :arg},
                                                            b {:form b,
                                                               :name b,
                                                               :variadic? false,
                                                               :op :binding,
                                                               :arg-id 1,
                                                               :local :arg}},
                                                   :ns anaphora.macros,
                                                   :loop-id loop_20646,
                                                   :file "/tmp/form-init4625432850048136597.clj",
                                                   :column 37,
                                                   :line 1,
                                                   :once false,
                                                   :context :ctx/expr},
                                             :o-tag java.lang.Object,
                                             :variadic? false,
                                             :arg-id 0,
                                             :form a,
                                             :tag java.lang.Object,
                                             :atom #object[clojure.lang.Atom
                                                           "0x1fc9405c"
                                                           {:status :ready,
                                                            :val {:tag java.lang.Object}}],
                                             :local :arg,
                                             :assignable? false}],
                                     :children [:args],
                                     :body? true,
                                     :method add,
                                     :op :static-call,
                                     :env {:loop-locals 2,
                                           :locals {x {:form x,
                                                       :name x,
                                                       :variadic? false,
                                                       :op :binding,
                                                       :arg-id 0,
                                                       :local :arg},
                                                    y {:form y,
                                                       :name y,
                                                       :variadic? false,
                                                       :op :binding,
                                                       :arg-id 1,
                                                       :local :arg},
                                                    a {:form a,
                                                       :name a,
                                                       :variadic? false,
                                                       :op :binding,
                                                       :arg-id 0,
                                                       :local :arg},
                                                    b {:form b,
                                                       :name b,
                                                       :variadic? false,
                                                       :op :binding,
                                                       :arg-id 1,
                                                       :local :arg}},
                                           :ns anaphora.macros,
                                           :loop-id loop_20646,
                                           :file "/tmp/form-init4625432850048136597.clj",
                                           :column 37,
                                           :line 1,
                                           :once false,
                                           :context :ctx/return},
                                     :o-tag java.lang.Number,
                                     :class clojure.lang.Numbers,
                                     :form (.
                                            clojure.lang.Numbers
                                            (add x a)),
                                     :tag java.lang.Number,
                                     :validated? true,
                                     :raw-forms ((do (+ x a)) (+ x a))}}],
                   :once false,
                   :max-fixed-arity 2,
                   :form (fn* ([a b] (+ x a))),
                   :tag clojure.lang.AFunction,
                   :arglists ([a b]),
                   :raw-forms ((do (fn [a b] (+ x a)))
                               (fn* ([a b] (+ x a)))
                               (fn [a b] (+ x a))
                               (fn [a b] (+ x a)))}}],
 :once false,
 :top-level true,
 :max-fixed-arity 2,
 :form (fn* ([x y] (fn [a b] (+ x a)))),
 :tag clojure.lang.AFunction,
 :arglists ([x y]),
 :raw-forms ((fn* ([x y] (fn [a b] (+ x a))))
             (fn [x y] (fn [a b] (+ x a)))
             (fn [x y] (fn [a b] (+ x a))))}
